Accelerate checking k8s-agents and k8s-controllers setup via 1 script
nxtlytics/ivy-ami-bakery pull request #40
Opened 2022-02-24 22:47 UTC by missingcharacter

```
$ cd /opt/ivy
$ ./k8s-agents -e -a -s 'k8s-controllers'
```

2022-02-24 23:08 UTC, samfreiberg-oh approved these changes
Just one minor grammatical question otherwise LGTM.

2022-02-24 23:08 UTC, samfreiberg-oh commented on roles/kubernetes/files/opt/ivy/k8s-check.sh
> +warn 'You may ran: tail -F /var/log/cloud-init*'
Should this be?: You may run: ...

2022-02-24 23:28 UTC, missingcharacter commented on roles/kubernetes/files/opt/ivy/k8s-check.sh
> +warn 'You may ran: tail -F /var/log/cloud-init*'
Yes, you are right, 1 moment

2022-02-28 14:54 UTC, lonnixOH requested changes

2022-02-28 14:59 UTC, lonnixOH approved these changes

2022-03-03 13:37 UTC, Pleshchuk approved these changes

2022-03-03 16:37 UTC, samfreiberg-oh approved these changes
LGTM

2022-03-04 22:24 UTC, merged